# Generated by Django 2.2.3 on 2019-07-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('inn', models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='ИНН заказчика')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН заказчика')),
                ('name_customer', models.CharField(blank=True, max_length=20, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Contarcts',
            fields=[
                ('number_contr', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер контракта')),
                ('txt_contacts', models.TextField(blank=True, null=True, verbose_name='Условия контракта')),
                ('date_pub', models.DateField(blank=True, verbose_name='Дата публикации')),
                ('date_rec', models.DateField(blank=True, verbose_name='Дата приёма')),
                ('sum_contr', models.PositiveIntegerField(blank=True, verbose_name='Сумма контракта')),
                ('close', models.BooleanField(blank=True, verbose_name='Закрыт')),
                ('cancel_contr', models.BooleanField(blank=True, verbose_name='Отменён')),
                ('deadline', models.BooleanField(blank=True, verbose_name='Превышение сроков')),
                ('fine', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Штрафные суммы')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Customers', verbose_name='Заказчик')),
                ('offer', models.ManyToManyField(related_name='contarcts_entity', to='entity.Entity', verbose_name='Контрагенты')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
