# Generated by Django 2.2.3 on 2019-07-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Бух баланс',
                'verbose_name_plural': 'Бух балансы',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('inn', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, verbose_name='ИНН')),
                ('name_entity', models.TextField(blank=True, verbose_name='Наименование')),
                ('form', models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], max_length=20, verbose_name='Форма')),
                ('ogrn', models.CharField(blank=True, max_length=25, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=25, verbose_name='КПП')),
                ('sur_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Фамилия ИП')),
                ('name_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Иимя ИП')),
                ('pat_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Отчество ИП')),
                ('date_reg', models.DateField(blank=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Статус')),
                ('date_stat', models.DateField(blank=True, verbose_name='Дата статуса')),
                ('date_term', models.DateField(blank=True, verbose_name='Дата прекращения')),
                ('capital', models.PositiveIntegerField(blank=True, verbose_name='Капитал суммы')),
                ('black_list', models.BooleanField(blank=True, verbose_name='Черный список')),
                ('number_stuff', models.IntegerField(blank=True, verbose_name='Численность персонала')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Юридическое лицо или ИП',
                'verbose_name_plural': 'Юридические лица или ИП',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('inn', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, verbose_name='ИНН руководителя')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Негативные показатели')),
            ],
            options={
                'verbose_name': 'Негативный показатель',
                'verbose_name_plural': 'Негативные показатели',
            },
        ),
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Код баланса')),
                ('sum', models.IntegerField(blank=True, verbose_name='Сумма')),
                ('year', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Balance', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Сумма за год',
                'verbose_name_plural': 'Суммы за года',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('series', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Серия')),
                ('date_start', models.DateField(blank=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, verbose_name='Дата конца')),
                ('activity', models.TextField(default=' ', verbose_name='Вид деятельности')),
                ('inn', models.ForeignKey(default='2724163941', on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='Лицензия')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('type', models.CharField(blank=True, choices=[('Юридическое лицо', 'Юридическое лицо'), ('Физическое лицо', 'Физическое лицо')], max_length=20, verbose_name='Тип')),
                ('sur_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Фамилия ИП')),
                ('name_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Иимя ИП')),
                ('pat_ip', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Отчество ИП')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Наименование')),
                ('date_reg', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.City', verbose_name='Адрес')),
                ('inn_entity', models.ForeignKey(blank=True, default='2724163941', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='Организация/ИП')),
            ],
            options={
                'verbose_name': 'Учредитель',
                'verbose_name_plural': 'Учредители',
            },
        ),
        migrations.CreateModel(
            name='Exec_Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('article', models.CharField(blank=True, max_length=20, verbose_name='Статья')),
                ('exec_proc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Leader', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='entity',
            name='negative',
            field=models.OneToOneField(blank=True, on_delete=None, to='entity.Negative', verbose_name='Негативные показатели'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Наименование')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.City', verbose_name='Адрес')),
                ('entity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='ЮР лицо')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='inn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='организация'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ОКВД')),
                ('name', models.TextField(blank=True, verbose_name='Наименование деятельности')),
                ('base', models.BooleanField(verbose_name='Основной вид деятельности')),
                ('activity', models.ManyToManyField(blank=True, related_name='activity_entity', to='entity.Entity', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельность',
            },
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('inn', 'year')},
        ),
    ]
