# Generated by Django 2.2.3 on 2019-07-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop_Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.BooleanField(verbose_name='Лиценизия действующая')),
                ('bankrupt', models.BooleanField(verbose_name='Банкрот')),
                ('acting', models.BooleanField(verbose_name='Действующий')),
                ('debt', models.BooleanField(verbose_name='Задолженность')),
                ('criminal', models.BooleanField(verbose_name='Судимость')),
                ('rights', models.BooleanField(verbose_name='Права')),
                ('ofhor', models.BooleanField(verbose_name='Офшорная компания')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Stop_Params', verbose_name='Параметры блокировки'),
        ),
    ]
