# Generated by Django 2.2.3 on 2019-07-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20190714_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop_params',
            name='relatives',
            field=models.BooleanField(default=1, verbose_name='Родственники'),
            preserve_default=False,
        ),
    ]
